### ISSUE TITLE
Enable looking around while driving - without steering

### ISSUE THREAD

**Issue by kevATin** [Flubberschnub/light-cycles#15]
I think it would make more sense for the bike to only steer into the direction you're looking in while you're holding the baton (have it selected in your hotbar).
That way drivers could look around while driving by simply switching away from the baton, and selecting it again when they want to change directions.

**Comment by Flubberschnub** [comment]
That's a good idea, but to implement that I'd first have to change how batons work in the inventory while riding.  I'll see what I can do
