### ISSUE TITLE
Option to disable derezzing via left click

### ISSUE THREAD

**Issue by kevATin** [Flubberschnub/light-cycles#16]
I think the de-rez via left click on the front wheel -feature could be used offensively to disrupt other players (in battle and in general).
So I'd rather only allow players to de-rez while steering the bike.
Could you add this as an option in the datapack?

**Comment by Flubberschnub** [comment]
It's actually only possible to derez via left-click if there is no player riding the bike, so that should work for you hopefully.

**Comment by kevATin** [comment]
I still think that could be used to disrupt gameplay by running around and punching parked bikes.
But I guess if it can't be used on others mid ride, that's good enough.

**Comment by Flubberschnub** [comment]
Yeah I wanted to keep it possible for people to steal bikes if they wanted to, allowing more agency for the player.  Batons aren't hardcoded to the player who currently owns them.

**Comment by kevATin** [comment]
I definitely approve of the ability to steal bikes, but isn't the baton inseparable from the bike anyways or did I misunderstand something?
Like if a random person jumps on a parked bike and derezzes it they get the baton, 
just like if a random person left clicks a parked bike and derezzes it and they get the baton.

That's how it currently works right? 
I have no problem with that, I just dislike the bike punching itself. I'd prefer if thiefs would have to jump onto a bike first in order to derezz it.

Does that make sense?
